[package]
name = "rdedupe"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = {version="4.0.32", features=["derive"]}
walkdir = "2.3.2"
md5 = "0.7.0"
rayon = "1.6.1"
indicatif = {version = "*", features = ["rayon"]}
polars = {version = "0.35", features = ["lazy", "csv"]}
num_cpus = "1.16"

[dev-dependencies]
assert_cmd = "2"
predicates = "2.0.0"